
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AspNetDeploy.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Bundle
{

    public Bundle()
    {

        this.BundleVersions = new HashSet<BundleVersion>();

        this.Projects = new HashSet<Project>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsSingleInstance { get; set; }

    public int OrderIndex { get; set; }



    public virtual ICollection<BundleVersion> BundleVersions { get; set; }

    public virtual ICollection<Project> Projects { get; set; }

}

}
