//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetDeploy.Model
{
    using System;
    
    public enum DeploymentStepType : int
    {
        Undefined = 0,
        DeployWebSite = 1,
        RunPowerShellScript = 2,
        CopyFiles = 3,
        Configuration = 4
    }
}
