//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetDeploy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvironmentChain
    {
        public int Id { get; set; }
        public int BundleVersionId { get; set; }
        public int NextEnvironmentId { get; set; }
        public int SourceEnvironmentId { get; set; }
    
        public virtual BundleVersion BundleVersion { get; set; }
        public virtual Environment Environment { get; set; }
        public virtual Environment Environment1 { get; set; }
    }
}
