//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetDeploy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionEntryData
    {
        public int Id { get; set; }
        public int ExceptionId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public bool IsProperty { get; set; }
    
        public virtual ExceptionEntry ExceptionEntry { get; set; }
    }
}
