
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AspNetDeploy.Model
{

using System;
    

public enum MachinePublicationLogEvent : int
{

    Undefined = 0,

    DeploymentStepConfiguring = 100,

    DeploymentStepConfiguringComplete = 101,

    DeploymentStepConfiguringError = 110,

    DeploymentStepExecuting = 200,

    DeploymentStepExecutingComplete = 201,

    DeploymentStepExecutingError = 210,

    DeploymentStepRollback = 300,

    DeploymentStepRollbackComplete = 301,

    DeploymentStepRollbackError = 310,

}

}
