//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetDeploy.Model
{
    using System;
    
    public enum MachinePublicationState : int
    {
        Undefined = 0,
        Queued = 1,
        Uploading = 2,
        Configuring = 3,
        Running = 4,
        Finalizing = 5,
        Complete = 6,
        Error = 7,
        Canceled = 8
    }
}
