//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetDeploy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine
    {
        public Machine()
        {
            this.Environments = new HashSet<Environment>();
            this.MachineRoles = new HashSet<MachineRole>();
            this.MachinePublication = new HashSet<MachinePublication>();
            this.DataFieldValues = new HashSet<DataFieldValue>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public string PublicKey { get; set; }
    
        public virtual ICollection<Environment> Environments { get; set; }
        public virtual ICollection<MachineRole> MachineRoles { get; set; }
        public virtual ICollection<MachinePublication> MachinePublication { get; set; }
        public virtual ICollection<DataFieldValue> DataFieldValues { get; set; }
    }
}
