//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetDeploy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public Package()
        {
            this.Publication = new HashSet<Publication>();
        }
    
        public int Id { get; set; }
        public int BundleVersionId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual BundleVersion BundleVersion { get; set; }
        public virtual ICollection<Publication> Publication { get; set; }
    }
}
