//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetDeploy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ProjectConfigurationField = new HashSet<ProjectConfigurationField>();
            this.Bundles = new HashSet<Bundle>();
            this.Properties = new HashSet<ProjectProperty>();
        }
    
        public int Id { get; set; }
        public int SourceControlId { get; set; }
        public string Name { get; set; }
        public string SolutionFile { get; set; }
        public ProjectType ProjectType { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> Guid { get; set; }
    
        public virtual SourceControl SourceControl { get; set; }
        public virtual ICollection<ProjectConfigurationField> ProjectConfigurationField { get; set; }
        public virtual ICollection<Bundle> Bundles { get; set; }
        public virtual ICollection<ProjectProperty> Properties { get; set; }
    }
}
