//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetDeploy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectConfigurationValue
    {
        public ProjectConfigurationValue()
        {
            this.Environment = new HashSet<Environment>();
        }
    
        public int Id { get; set; }
        public int ProjectConfigurationFieldId { get; set; }
        public string Value { get; set; }
    
        public virtual ProjectConfigurationField ProjectConfigurationField { get; set; }
        public virtual ICollection<Environment> Environment { get; set; }
    }
}
