//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetDeploy.Model
{
    using System;
    
    public enum ProjectType : int
    {
        Undefined = 0,
        Web = 1,
        Console = 2,
        Service = 3,
        ClassLibrary = 4,
        Deployment = 5,
        Database = 6,
        Test = 7
    }
}
