
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AspNetDeploy.Model
{

using System;
    

public enum PublicationState : int
{

    Undefined = 0,

    NotStarted = 1,

    InProgress = 2,

    Canceled = 3,

    Error = 4,

    Complete = 5,

    Queued = 6,

}

}
