
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AspNetDeploy.Model
{

using System;
    using System.Collections.Generic;
    
public partial class RevisionInfo
{

    public int Id { get; set; }

    public int RevisionId { get; set; }

    public string Message { get; set; }

    public string Author { get; set; }

    public System.DateTime CreatedDate { get; set; }



    public virtual Revision Revision { get; set; }

}

}
