//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetDeploy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceControlVersion
    {
        public SourceControlVersion()
        {
            this.ProjectVersions = new HashSet<ProjectVersion>();
            this.Properties = new HashSet<SourceControlVersionProperty>();
        }
    
        public int Id { get; set; }
        public int SourceControlId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ProjectVersion> ProjectVersions { get; set; }
        public virtual SourceControl SourceControl { get; set; }
        public virtual ICollection<SourceControlVersionProperty> Properties { get; set; }
    }
}
