//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetDeploy.Model
{
    using System;
    
    public enum SourceControlType : int
    {
        Undefined = 0,
        Svn = 1,
        Git = 2,
        FileSystem = 3
    }
}
