//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetDeploy.Model
{
    using System;
    
    public enum SourceControlVersionWorkState : int
    {
        Undefined = 0,
        LoadRequired = 1,
        Loading = 2,
        Normal = 3,
        ArchiveRequired = 4,
        Archiving = 5,
        Archived = 6
    }
}
