//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Environment
    {
        public Environment()
        {
            this.Machines = new HashSet<Machine>();
            this.ProjectConfigurationValue = new HashSet<ProjectConfigurationValue>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Machine> Machines { get; set; }
        public virtual ICollection<ProjectConfigurationValue> ProjectConfigurationValue { get; set; }
    }
}
