//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine
    {
        public Machine()
        {
            this.Environment = new HashSet<Environment>();
            this.MachineRole = new HashSet<MachineRole>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string PrivateKey { get; set; }
        public string URL { get; set; }
    
        public virtual ICollection<Environment> Environment { get; set; }
        public virtual ICollection<MachineRole> MachineRole { get; set; }
    }
}
